# Generated by Django 5.2.8 on 2025-11-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColisEnvoye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=32, unique=True, verbose_name='Référence')),
                ('statut', models.CharField(choices=[('OK', 'OK'), ('ATT', 'À vérifier'), ('LIVR', 'Livré')], default='ATT', max_length=4, verbose_name='ST')),
                ('expediteur_nom', models.CharField(max_length=120, verbose_name='Expéditeur')),
                ('expediteur_tel', models.CharField(blank=True, max_length=32, verbose_name='Téléphone expéditeur')),
                ('destinataire_nom', models.CharField(max_length=120, verbose_name='Destinataire')),
                ('destinataire_tel', models.CharField(blank=True, max_length=32, verbose_name='Téléphone destinataire')),
                ('prix_euros', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Prix (€)')),
                ('type_colis', models.CharField(blank=True, max_length=50, verbose_name='Liste colis')),
                ('poids_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Poids (kg)')),
                ('date_envoi', models.DateField(verbose_name='Date envoi')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_envoi', '-created_at'],
            },
        ),
    ]
