# Generated by Django 5.2.8 on 2025-11-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_colisenvoye'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exp_tel', models.CharField(blank=True, max_length=32, verbose_name='Téléphone expéditeur')),
                ('exp_nom', models.CharField(max_length=120, verbose_name='Nom expéditeur')),
                ('exp_prenom', models.CharField(blank=True, max_length=120, verbose_name='Prénom expéditeur')),
                ('exp_mail', models.EmailField(blank=True, max_length=254, verbose_name='Mail expéditeur')),
                ('exp_adresse', models.CharField(blank=True, max_length=200, verbose_name='Adresse postale')),
                ('des_tel', models.CharField(blank=True, max_length=32, verbose_name='Téléphone destinataire')),
                ('des_nom', models.CharField(max_length=120, verbose_name='Nom destinataire')),
                ('des_prenom', models.CharField(blank=True, max_length=120, verbose_name='Prénom destinataire')),
                ('des_mail', models.EmailField(blank=True, max_length=254, verbose_name='Mail destinataire')),
                ('des_agence', models.CharField(blank=True, max_length=120, verbose_name='Agence')),
                ('livraison', models.BooleanField(default=False, verbose_name='Livraison')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Description')),
                ('produit', models.CharField(blank=True, max_length=120, verbose_name='Produit / référence')),
                ('qui_paye', models.CharField(choices=[('EXP', 'Expéditeur'), ('DES', 'Destinataire'), ('AUT', 'Autre')], default='EXP', max_length=3, verbose_name='Qui paye ?')),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Montant')),
                ('devise', models.CharField(default='EUR', max_length=8, verbose_name='Devise')),
                ('date_colis', models.DateField(verbose_name='Date')),
                ('ref_colis', models.CharField(max_length=64, verbose_name='Réf colis')),
                ('type_piece', models.CharField(choices=[('FACTURE', 'FACTURE'), ('AVOIR', 'AVOIR')], default='FACTURE', max_length=16, verbose_name='TYPE')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
