# Generated by Django 5.2.8 on 2025-11-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_facture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facture',
            name='type_piece',
            field=models.CharField(choices=[('FACTURE', 'FACTURE'), ('DEVIS', 'DEVIS'), ('AVOIR', 'AVOIR')], default='FACTURE', max_length=16, verbose_name='TYPE'),
        ),
    ]
