# Generated by Django 5.2.8 on 2025-11-11 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_facture_type_piece'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationComptable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('libelle', models.CharField(max_length=160)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sens', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie')], max_length=6)),
                ('mode', models.CharField(choices=[('ESPECES', 'Espèces'), ('BANQUE', 'Banque'), ('AUTRE', 'Autre')], default='ESPECES', max_length=8)),
                ('agence', models.CharField(choices=[('PARIS', 'PARIS'), ('ROISSY', 'ROISSY')], default='PARIS', max_length=20)),
                ('ref_colis', models.CharField(blank=True, max_length=64)),
                ('utilisateur', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date_colis', '-created_at']},
        ),
        migrations.AlterField(
            model_name='colisenvoye',
            name='date_envoi',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='colisenvoye',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='colisenvoye',
            name='destinataire_nom',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='colisenvoye',
            name='destinataire_tel',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='colisenvoye',
            name='expediteur_nom',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='colisenvoye',
            name='expediteur_tel',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='colisenvoye',
            name='poids_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='colisenvoye',
            name='prix_euros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='colisenvoye',
            name='reference',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='colisenvoye',
            name='statut',
            field=models.CharField(choices=[('OK', 'OK'), ('ATT', 'À vérifier'), ('LIVR', 'Livré')], default='ATT', max_length=4),
        ),
        migrations.AlterField(
            model_name='colisenvoye',
            name='type_colis',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='colisrecu',
            name='date_enregistrement',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='colisrecu',
            name='description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='colisrecu',
            name='destinataire_nom',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='colisrecu',
            name='destinataire_tel',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='colisrecu',
            name='expediteur_nom',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='colisrecu',
            name='expediteur_tel',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='colisrecu',
            name='livraison',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='colisrecu',
            name='nbs',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='colisrecu',
            name='poids_kg',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='colisrecu',
            name='reference',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='colisrecu',
            name='restant_euros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='colisrecu',
            name='statut',
            field=models.CharField(choices=[('OK', 'OK'), ('ATT', 'À vérifier'), ('LIVR', 'Livré')], default='ATT', max_length=4),
        ),
        migrations.AlterField(
            model_name='colisrecu',
            name='type_colis',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
