# Generated by Django 5.2.8 on 2025-11-15 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_operationcomptable_alter_facture_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ballon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Ex: BAL001, BAL B3, etc.', max_length=32, unique=True)),
                ('type_ballon', models.CharField(choices=[('23KG', 'BALLON 23 KG'), ('32KG', 'BALLON 32 KG')], default='23KG', max_length=5)),
                ('agence_destination', models.CharField(choices=[('PARIS', 'PARIS AGENCE'), ('MATOTO', 'MATOTO'), ('ROISSY', 'ROISSY')], default='PARIS', max_length=20)),
                ('commentaire', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(default='EN PRÉPA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BallonItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=64)),
                ('poids_kg', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('ballon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='gestion.ballon')),
            ],
            options={
                'ordering': ['ordre', 'id'],
            },
        ),
    ]
