# Generated by Django 5.2.8 on 2026-02-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_smsmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='colisrecu',
            name='prix_fret_euros',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='colisrecu',
            name='type_fret',
            field=models.CharField(choices=[('AERIEN', 'Fret aérien'), ('MARITIME', 'Fret maritime')], default='AERIEN', max_length=10),
        ),
    ]
