# Generated by Django 5.2.8 on 2026-02-28 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0008_colisrecu_prix_fret_euros_colisrecu_type_fret'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colisrecu',
            name='reference',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
