# Generated by Django 5.2.8 on 2026-02-28 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_alter_colisrecu_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colisrecu',
            name='restant_euros',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
    ]
