# Generated by Django 5.2.8 on 2026-03-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_alter_colisrecu_restant_euros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colisrecu',
            name='prix_fret_euros',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='colisrecu',
            name='reference',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
