# Generated by Django 5.2.8 on 2026-03-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0011_alter_colisrecu_prix_fret_euros_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colisrecu',
            name='agent_nom',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='colisrecu',
            name='nb_colis_recus',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='colisrecu',
            name='nb_colis_total',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
