# Generated by Django 5.2.8 on 2026-03-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0012_colisrecu_agent_nom_colisrecu_nb_colis_recus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransfertArgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(blank=True, max_length=6, unique=True)),
                ('statut', models.CharField(choices=[('ATT', 'En attente'), ('OK', 'Validé'), ('PAYE', 'Payé'), ('ANNULE', 'Annulé')], default='ATT', max_length=10)),
                ('agent_nom', models.CharField(blank=True, max_length=120)),
                ('expediteur_nom', models.CharField(max_length=120)),
                ('expediteur_tel', models.CharField(blank=True, max_length=32)),
                ('destinataire_nom', models.CharField(max_length=120)),
                ('destinataire_tel', models.CharField(blank=True, max_length=32)),
                ('devise_envoi', models.CharField(choices=[('EUR', 'Euro (EUR)'), ('GNF', 'Franc guinéen (GNF)')], default='EUR', max_length=3)),
                ('devise_reception', models.CharField(choices=[('EUR', 'Euro (EUR)'), ('GNF', 'Franc guinéen (GNF)')], default='GNF', max_length=3)),
                ('montant_envoye', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('taux_transfert', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('montant_reception', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=14)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('date_transfert', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_transfert', '-created_at'],
            },
        ),
    ]
