# Generated by Django 5.2.8 on 2026-03-08 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0013_transfertargent'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfertargent',
            name='date_retrait',
            field=models.DateField(blank=True, null=True),
        ),
    ]
