# Generated by Django 5.2.8 on 2026-03-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0014_transfertargent_date_retrait'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colisrecu',
            name='nb_colis_recus',
        ),
        migrations.AddField(
            model_name='colisrecu',
            name='agence_destination',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='colisrecu',
            name='expediteur_adresse',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
