# Generated by Django 5.2.8 on 2026-03-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0015_remove_colisrecu_nb_colis_recus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfertargent',
            name='devise_envoi',
            field=models.CharField(choices=[('EUR', 'Euro'), ('GNF', 'Franc guinéen')], default='EUR', max_length=3),
        ),
        migrations.AlterField(
            model_name='transfertargent',
            name='devise_reception',
            field=models.CharField(choices=[('EUR', 'Euro'), ('GNF', 'Franc guinéen')], default='GNF', max_length=3),
        ),
        migrations.AlterField(
            model_name='transfertargent',
            name='statut',
            field=models.CharField(choices=[('ATT', 'À vérifier'), ('OK', 'En cours'), ('PAYE', 'Retiré'), ('ANN', 'Annulé')], default='ATT', max_length=4),
        ),
    ]
