# Generated by Django 5.2.8 on 2026-03-15 16:17

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0016_alter_transfertargent_devise_envoi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfertargent',
            name='frais_pourcentage',
            field=models.DecimalField(blank=True, choices=[(Decimal('1.0'), '1%'), (Decimal('1.5'), '1,5%'), (Decimal('2.0'), '2%'), (Decimal('2.5'), '2,5%'), (Decimal('3.0'), '3%'), (Decimal('3.5'), '3,5%'), (Decimal('4.0'), '4%'), (Decimal('4.5'), '4,5%'), (Decimal('5.0'), '5%')], decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name='transfertargent',
            name='frais_transfert',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='transfertargent',
            name='montant_total_payer',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
