# Generated by Django 5.2.8 on 2026-03-22 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0017_transfertargent_frais_pourcentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30)),
                ('client_nom', models.CharField(blank=True, max_length=150, null=True)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('success', 'Succès'), ('error', 'Erreur')], default='success', max_length=20)),
                ('provider', models.CharField(default='brevo', max_length=50)),
                ('provider_message_id', models.CharField(blank=True, max_length=100, null=True)),
                ('erreur', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
