# Generated by Django 5.2.8 on 2026-03-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0019_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colisrecu',
            name='statut',
            field=models.CharField(choices=[('PEC', 'Pris en charge'), ('ECR', 'En cours'), ('ARR', 'Arrivée'), ('LIVR', 'Livré')], default='PEC', max_length=4),
        ),
    ]
