# Generated by Django 5.2.8 on 2026-03-27 15:10

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0020_alter_colisrecu_statut'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(default='AD Logistics', max_length=150)),
                ('sous_titre', models.CharField(blank=True, max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='parametres/factures/')),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('telephone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('site_web', models.CharField(blank=True, max_length=255)),
                ('devise_defaut', models.CharField(default='EUR', max_length=8)),
                ('taux_tva_defaut', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('delai_paiement_jours', models.PositiveIntegerField(default=7)),
                ('prefixe_facture', models.CharField(default='FAC', max_length=20)),
                ('prefixe_devis', models.CharField(default='DEV', max_length=20)),
                ('prefixe_avoir', models.CharField(default='AV', max_length=20)),
                ('prochain_numero_facture', models.PositiveIntegerField(default=1)),
                ('prochain_numero_devis', models.PositiveIntegerField(default=1)),
                ('prochain_numero_avoir', models.PositiveIntegerField(default=1)),
                ('iban', models.CharField(blank=True, max_length=80)),
                ('bic', models.CharField(blank=True, max_length=50)),
                ('texte_entete', models.TextField(blank=True)),
                ('conditions_reglement', models.TextField(blank=True)),
                ('pied_facture', models.TextField(blank=True)),
                ('modele_email_sujet', models.CharField(default='Votre {type_piece} {numero} - {entreprise}', max_length=255)),
                ('modele_email_message', models.TextField(default='Bonjour {client_nom},\n\nVeuillez trouver ci-joint votre {type_piece} {numero} relatif(ve) au colis {ref_colis}.\n\nMontant total : {total_ttc} {devise}\n\nCordialement,\n{entreprise}')),
                ('couleur_primaire', models.CharField(default='#0f172a', max_length=20)),
                ('afficher_logo', models.BooleanField(default=True)),
                ('afficher_iban_bic', models.BooleanField(default=True)),
                ('afficher_conditions', models.BooleanField(default=True)),
                ('afficher_bloc_expediteur', models.BooleanField(default=True)),
                ('afficher_bloc_destinataire', models.BooleanField(default=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre de facturation',
                'verbose_name_plural': 'Paramètres de facturation',
            },
        ),
        migrations.AlterModelOptions(
            name='facture',
            options={'ordering': ['-date_facture', '-created_at'], 'verbose_name': 'Facture / Devis / Avoir', 'verbose_name_plural': 'Factures / Devis / Avoir'},
        ),
        migrations.RemoveField(
            model_name='facture',
            name='montant',
        ),
        migrations.AddField(
            model_name='facture',
            name='cree_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestion_factures_creees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_echeance',
            field=models.DateField(blank=True, null=True, verbose_name='Date échéance'),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_envoi_email',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date envoi e-mail'),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_facture',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Date facture'),
        ),
        migrations.AddField(
            model_name='facture',
            name='date_paiement',
            field=models.DateField(blank=True, null=True, verbose_name='Date paiement'),
        ),
        migrations.AddField(
            model_name='facture',
            name='des_adresse',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adresse postale destinataire'),
        ),
        migrations.AddField(
            model_name='facture',
            name='modifie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gestion_factures_modifiees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_ht',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant HT'),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_paye',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant payé'),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_ttc',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant TTC'),
        ),
        migrations.AddField(
            model_name='facture',
            name='montant_tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Montant TVA'),
        ),
        migrations.AddField(
            model_name='facture',
            name='nb_colis',
            field=models.PositiveIntegerField(default=1, verbose_name='Nombre de colis'),
        ),
        migrations.AddField(
            model_name='facture',
            name='note_client',
            field=models.TextField(blank=True, verbose_name='Note client'),
        ),
        migrations.AddField(
            model_name='facture',
            name='note_interne',
            field=models.TextField(blank=True, verbose_name='Note interne'),
        ),
        migrations.AddField(
            model_name='facture',
            name='numero',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Numéro'),
        ),
        migrations.AddField(
            model_name='facture',
            name='poids_kg',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Poids (kg)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='remise',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Remise'),
        ),
        migrations.AddField(
            model_name='facture',
            name='reste_a_payer',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, verbose_name='Reste à payer'),
        ),
        migrations.AddField(
            model_name='facture',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('VALIDE', 'Validé'), ('ENVOYEE', 'Envoyée'), ('PARTIEL', 'Partiellement payée'), ('PAYEE', 'Payée'), ('RETARD', 'En retard'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20),
        ),
        migrations.AddField(
            model_name='facture',
            name='taux_tva',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='TVA (%)'),
        ),
        migrations.AddField(
            model_name='facture',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='facture',
            name='date_colis',
            field=models.DateField(verbose_name='Date colis'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='des_agence',
            field=models.CharField(blank=True, max_length=120, verbose_name='Agence destination'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='exp_adresse',
            field=models.CharField(blank=True, max_length=200, verbose_name='Adresse postale expéditeur'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='ref_colis',
            field=models.CharField(db_index=True, max_length=64, verbose_name='Réf colis'),
        ),
        migrations.CreateModel(
            name='HistoriqueEnvoiFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_destinataire', models.EmailField(max_length=254)),
                ('sujet', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('succes', models.BooleanField(default=False)),
                ('erreur', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('envoye_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envois_email', to='gestion.facture')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaiementFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_paiement', models.DateField(default=django.utils.timezone.localdate)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement'), ('CB', 'Carte bancaire'), ('CHEQUE', 'Chèque'), ('MOBILE', 'Mobile Money'), ('AUTRE', 'Autre')], default='ESPECES', max_length=20)),
                ('reference_paiement', models.CharField(blank=True, max_length=100)),
                ('commentaire', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='gestion.facture')),
            ],
            options={
                'ordering': ['-date_paiement', '-created_at'],
            },
        ),
    ]
