# Generated by Django 5.2.8 on 2026-03-28 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0021_parametrefacture_alter_facture_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='pdf_archive',
            field=models.FileField(blank=True, null=True, upload_to='factures/pdf/', verbose_name='PDF archivé'),
        ),
        migrations.AddField(
            model_name='facture',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='factures/qrcodes/', verbose_name='QR code'),
        ),
        migrations.AlterField(
            model_name='historiqueenvoifacture',
            name='email_destinataire',
            field=models.TextField(),
        ),
    ]
