# Generated by Django 5.2.8 on 2026-03-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parametre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cle', models.CharField(max_length=100, unique=True)),
                ('libelle', models.CharField(max_length=150)),
                ('valeur', models.TextField(blank=True, default='')),
                ('type_valeur', models.CharField(choices=[('text', 'Texte'), ('number', 'Nombre'), ('bool', 'Oui / Non'), ('email', 'Email'), ('phone', 'Téléphone'), ('date', 'Date')], default='text', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('modifiable', models.BooleanField(default=True)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Paramètre',
                'verbose_name_plural': 'Paramètres',
                'ordering': ['ordre', 'libelle'],
            },
        ),
    ]
