# Generated by Django 5.2.8 on 2026-03-24 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_agence'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrepriseCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('adresse', models.CharField(blank=True, max_length=255)),
                ('ville', models.CharField(blank=True, max_length=120)),
                ('pays', models.CharField(default='France', max_length=120)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='entreprises/logos/')),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entreprise cliente',
                'verbose_name_plural': 'Entreprises clientes',
                'ordering': ['nom'],
            },
        ),
        migrations.AlterField(
            model_name='agence',
            name='code',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='cle',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='agence',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Agences', to='administration.entreprisecliente'),
        ),
        migrations.AddField(
            model_name='parametre',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entreprise', to='administration.entreprisecliente'),
        ),
        migrations.AlterUniqueTogether(
            name='agence',
            unique_together={('entreprise', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='parametre',
            unique_together={('entreprise', 'cle')},
        ),
    ]
