# Generated by Django 5.2.8 on 2026-03-24 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_entreprisecliente_alter_agence_code_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN_CLIENT', 'Admin client'), ('CHEF_AGENCE', "Chef d'agence"), ('AGENT', 'Agent'), ('CAISSE', 'Caisse'), ('LECTURE', 'Lecture seule')], default='AGENT', max_length=20)),
                ('actif', models.BooleanField(default=True)),
                ('peut_gerer_agences', models.BooleanField(default=False)),
                ('peut_gerer_agents', models.BooleanField(default=False)),
                ('peut_gerer_parametres', models.BooleanField(default=False)),
                ('peut_gerer_sms', models.BooleanField(default=False)),
                ('peut_voir_factures', models.BooleanField(default=False)),
                ('peut_voir_rapports', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('agence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='administration.agence')),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='administration.entreprisecliente')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_agent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil agent',
                'verbose_name_plural': 'Profils agents',
                'ordering': ['user__username'],
            },
        ),
    ]
