# Generated by Django 5.2.8 on 2026-03-25 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0004_profilagent'),
    ]

    operations = [
        migrations.CreateModel(
            name='VilleLivraison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=120)),
                ('pays', models.CharField(default='Guinée', max_length=120)),
                ('zone', models.CharField(blank=True, max_length=120)),
                ('frais_livraison', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delai_estime_jours', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='villes_livraison', to='administration.entreprisecliente')),
            ],
            options={
                'verbose_name': 'Ville de livraison',
                'verbose_name_plural': 'Villes de livraison',
                'ordering': ['entreprise__nom', 'nom'],
                'unique_together': {('entreprise', 'nom')},
            },
        ),
    ]
