# Generated by Django 5.2.8 on 2026-03-25 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_villelivraison'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fournisseur', models.CharField(choices=[('BREVO', 'Brevo'), ('TWILIO', 'Twilio'), ('AUTRE', 'Autre')], default='BREVO', max_length=30)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('sender_name', models.CharField(blank=True, max_length=50)),
                ('sms_actif', models.BooleanField(default=False)),
                ('modele_creation', models.TextField(blank=True)),
                ('modele_arrivee', models.TextField(blank=True)),
                ('modele_livraison', models.TextField(blank=True)),
                ('modele_transfert', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('entreprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='param_sms', to='administration.entreprisecliente')),
            ],
            options={
                'verbose_name': 'Paramétrage SMS',
                'verbose_name_plural': 'Paramétrages SMS',
                'ordering': ['entreprise__nom'],
            },
        ),
    ]
