# Generated by Django 5.2.8 on 2026-03-25 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_parametresms'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='agence',
            name='entreprise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agences', to='administration.entreprisecliente'),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='entreprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parametres', to='administration.entreprisecliente'),
        ),
        migrations.CreateModel(
            name='HistoriqueAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('DELETE', 'Suppression'), ('LOGIN', 'Connexion'), ('LOGOUT', 'Déconnexion'), ('OTHER', 'Autre')], default='OTHER', max_length=20)),
                ('module', models.CharField(max_length=100)),
                ('objet', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_actions', to='administration.entreprisecliente')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historiques_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Historique d'action",
                'verbose_name_plural': 'Historique des actions',
                'ordering': ['-date_action'],
            },
        ),
    ]
