# Generated by Django 5.2.8 on 2026-03-25 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_alter_agence_entreprise_alter_parametre_entreprise_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True)),
                ('type_facture', models.CharField(choices=[('ABONNEMENT', 'Abonnement'), ('RENOUVELLEMENT', 'Renouvellement'), ('SERVICE', 'Service'), ('AUTRE', 'Autre')], default='ABONNEMENT', max_length=20)),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('EMISE', 'Émise'), ('PAYEE', 'Payée'), ('PARTIEL', 'Paiement partiel'), ('ANNULEE', 'Annulée')], default='BROUILLON', max_length=20)),
                ('date_emission', models.DateField()),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('periode_debut', models.DateField(blank=True, null=True)),
                ('periode_fin', models.DateField(blank=True, null=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('montant_ttc', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('devise', models.CharField(default='EUR', max_length=10)),
                ('mode_paiement', models.CharField(blank=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('observations', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factures_creees', to=settings.AUTH_USER_MODEL)),
                ('entreprise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factures', to='administration.entreprisecliente')),
            ],
            options={
                'verbose_name': 'Facture client',
                'verbose_name_plural': 'Factures clients',
                'ordering': ['-date_emission', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RapportConnexion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(blank=True, max_length=150)),
                ('nom_complet_snapshot', models.CharField(blank=True, max_length=255)),
                ('date_connexion', models.DateTimeField()),
                ('date_deconnexion', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('statut', models.CharField(choices=[('CONNECTE', 'Connecté'), ('DECONNECTE', 'Déconnecté')], default='CONNECTE', max_length=20)),
                ('agence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_connexions', to='administration.agence')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_connexions', to='administration.entreprisecliente')),
                ('utilisateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rapports_connexions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rapport de connexion',
                'verbose_name_plural': 'Rapports de connexion',
                'ordering': ['-date_connexion'],
            },
        ),
    ]
