# Generated by Django 5.2.8 on 2026-03-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_factureclient_rapportconnexion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parametre',
            options={'ordering': ['categorie', 'ordre', 'libelle'], 'verbose_name': 'Paramètre', 'verbose_name_plural': 'Paramètres'},
        ),
        migrations.AddField(
            model_name='parametre',
            name='categorie',
            field=models.CharField(choices=[('IDENTITE', 'Identité société'), ('CONTACT', 'Coordonnées'), ('AFFICHAGE', 'Affichage'), ('FACTURATION', 'Facturation'), ('REFERENCES', 'Références'), ('TRACKING', 'Tracking / QR Code'), ('AUTRE', 'Autre')], default='AUTRE', max_length=30),
        ),
        migrations.AlterField(
            model_name='parametre',
            name='type_valeur',
            field=models.CharField(choices=[('text', 'Texte'), ('number', 'Nombre'), ('bool', 'Oui / Non'), ('email', 'Email'), ('phone', 'Téléphone'), ('date', 'Date'), ('textarea', 'Texte long'), ('color', 'Couleur'), ('image', 'Image'), ('url', 'URL')], default='text', max_length=20),
        ),
    ]
