# Generated by Django 5.2.8 on 2026-03-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_alter_factureclient_cree_par'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametre',
            name='fichier',
            field=models.ImageField(blank=True, null=True, upload_to='parametres/'),
        ),
    ]
